### ISSUE TITLE
Your code does not seem to work? 

### ISSUE THREAD

**Issue by yosun** [autonomousvision/LaRa#4]
Trying to run each of your documented use cases but none of them seem to work. Could you please provide some working code? 

### multi-view to 3D
`python eval_all.py`
does not seem to produce the multiview to 3d unlike what is advertised 

### text to 3D
````
python evaluation.py configs/infer.yaml 
       infer.ckpt_path=ckpts/lara.ckpt
       infer.save_folder=outputs/prompts/
       infer.dataset.generator_type=instant3d
       infer.dataset.prompts=["a car made out of sushi","a beautiful rainbow fish"]
````
your instantmesh implementation is not done, so an exception occurs 

### single view to 3D
````
python evaluation.py configs/infer.yaml 
       infer.ckpt_path=ckpts/lara.ckpt
       infer.save_folder=outputs/single-view/
       infer.dataset.generator_type="zero123plus-v1.1"
       infer.dataset.image_pathes=\["assets/examples/19_dalle3_stump1.png"\]
````
we used a 1024x1024 image for 19_dalle3_stump1.png and got this error 
`index 3 is out of bounds for dimension 1 with size 3`

**Comment by apchenstu** [comment]
**multi-view to 3D**
please specify the video_frames and save_mesh [labels](https://github.com/autonomousvision/LaRa/blob/main/eval_all.py#L11) if you would like to output mesh and video during the evaluation

**text to 3D** and **single view to 3D**
Please pull and try again, sorry for the outdated readme and dataloader

**Comment by yosun** [comment]
just want to check if downloading gobjecverse is required for multiview to 3d inference only?

**Comment by apchenstu** [comment]
Yes, you can download other datasets like google_scancel_objects by specify gso [here](https://github.com/autonomousvision/LaRa/blob/main/tools/download_dataset.py#L41)
