### ISSUE TITLE
Input of the method

### ISSUE THREAD

**Issue by chenhonghua** [autonomousvision/LaRa#6]
Hi, 

Are the results generated by mvdream suitable for this approach?
If so, how can mvdream be adapted to this framework?

**Comment by apchenstu** [comment]
Thanks for the question. 
Our method is a feed-forward multi-view reconstruction method, so the input is basically posed multi-view images. The multi-view images can be real captured images or generated images. 
You can also generate images by mvdream.

**Comment by chenhonghua** [comment]
Thanks!
